title: Allen's Blog
description: A blog about tech, science, and interdisciplinary studies
url: "https://allenkang92.github.io"
github_username: allenkang92

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Custom settings
author: Allen Kang
email: ksw8841@knou.ac.kr

# Collections
collections:
  categories:
    output: true

# Category structure
category_structure:
  기술:
    subcategories:
      프로그래밍:
        - Python
        - Java
      데이터 과학: []
  과학:
    subcategories:
      물리학: []
      생명과학: []

# Defaults
defaults:
  - scope:
      path: ""
      type: categories
    values:
      layout: category