# Site settings
title: Allen's Blog
description: Striving for a better tomorrow, together with you.
url: "https://allenkang92.github.io"
github_username: allenkang92
author: Allen Kang
email: ksw8841@knou.ac.kr
baseurl: ""

# Build settings
markdown: kramdown
theme: minima
future: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

# Directory settings
source: .
destination: ./_site
layouts_dir: _layouts
includes_dir: _includes
data_dir: _data

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - package.json
  - package-lock.json
  - webpack.config.js
  - .babelrc
  - README.md

# Collections
collections:
  posts:
    output: true
    permalink: /posts/:title/
  achievements:
    output: true
    permalink: /achievements/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      permalink: /posts/:title/
  - scope:
      path: ""
      type: "achievements"
    values:
      layout: "achievement"
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "page"

# Include
include:
  - _pages