# Site settings
title: Allen's Blog
description: 쌍문동 민초단 지부장 | Aspirant in Cognitive Science and Neuroscience | Physics Imp | Future Science Communicator
url: "https://allenkang92.github.io"
github_username: allenkang92
author: Allen Kang
email: ksw8841@knou.ac.kr

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-lunr-js-search

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Navigation menu
navigation:
  - title: Home
    url: /
  - title: Posts
    url: /posts.html
  - title: Achievements
    url: /achievements.html
  - title: Tools
    url: /tools.html
  - title: About
    url: /about.html

# Collections
collections:
  categories:
    output: true
    permalink: /categories/:name/
  tools:
    output: true
  series:
    output: true
    permalink: /series/:name/

# Category structure for the blog
category_structure:
  programming:
    title: Programming
    subcategories:
      - python
      - java
      - web-automation
  data_science:
    title: Data Science
    subcategories:
      - data_analysis
      - machine_learning
      - deep_learning
      - data_visualization
  devops_&_cloud:
    title: DevOps & Cloud
    subcategories:
      - containerization
      - cloud_computing
      - orchestration
      - version_control
      - monitoring
  data_engineering:
    title: Data Engineering
    subcategories:
      - etl
      - stream_processing
  computer_science:
    title: Computer Science
    subcategories:
      - algorithms
      - data_structures
      - databases
      - networking
      - security
      - operating_systems
      - computer_architecture
      - software_engineering
      - programming_languages
      - quantum_computing
  bioinformatics:
    title: Bioinformatics
    subcategories:
      - genomics
      - proteomics
      - biopython
      - life_sciences
  science_philosophy_history:
    title: Science Philosophy & History
    subcategories:
      - philosophy_of_science
      - history_of_science
  mathematics_philosophy_history:
    title: Mathematics Philosophy & History
    subcategories:
      - philosophy_of_mathematics
      - history_of_mathematics
  web_technologies:
    title: Web Technologies
    subcategories:
      - html_css
      - javascript
      - web_frameworks
  design:
    title: Design
    subcategories:
      - ui_ux
      - graphic_design
  physics:
    title: Physics
    subcategories:
      - classical_mechanics
      - quantum_mechanics
      - relativity
  chemistry:
    title: Chemistry
    subcategories:
      - organic_chemistry
      - inorganic_chemistry
      - physical_chemistry
  cognitive_science:
    title: Cognitive Science
    subcategories:
      - cognitive_psychology
      - neuroscience
      - artificial_intelligence
  human_factors_engineering:
    title: Human Factors Engineering
    subcategories:
      - ergonomics
      - human_computer_interaction
  environmental_science:
    title: Environmental Science
    subcategories:
      - climate_change
      - sustainability
  social_impact:
    title: Social Impact
    subcategories:
      - technology_ethics
      - social_innovation
  sports_science:
    title: Sports Science
    subcategories:
      - biomechanics
      - exercise_physiology
  law:
    title: Law
    subcategories:
      - intellectual_property
      - technology_law
  mechanical_engineering:
    title: Mechanical Engineering
    subcategories:
      - thermodynamics
      - fluid_mechanics
  atmospheric_science:
    title: Atmospheric Science
    subcategories:
      - meteorology
      - climatology
  psychology:
    title: Psychology
    subcategories:
      - cognitive_psychology
      - social_psychology