# Site settings
title: Allen's Blog
description: A blog about tech, science, and interdisciplinary studies
url: "https://allenkang92.github.io"
github_username: allenkang92
author: Allen Kang
email: ksw8841@knou.ac.kr

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Navigation menu
navigation:
  - title: Home
    url: /
  - title: Posts
    url: /posts.html
  - title: Achievements
    url: /achievements.html
  - title: Tools
    url: /tools.html
  - title: About
    url: /about.html

# Collections
collections:
  categories:
    output: true
  achievements:
    output: true
  tools:
    output: true

# Category structure
category_structure:
  programming:
    title: Programming
    subcategories:
      - python
      - java
      - web-automation
  data_science:
    title: Data Science
    subcategories:
      - machine_learning
      - data_analysis
      - data_visualization
  devops:
    title: DevOps & Cloud
    subcategories:
      - containerization
      - cloud_computing
      - orchestration
      - version_control
      - monitoring
  data_engineering:
    title: Data Engineering
    subcategories:
      - etl
      - stream_processing
  bioinformatics:
    title: Bioinformatics
    subcategories:
      - genomics
      - proteomics
  science_philosophy:
    title: Science Philosophy & History
    subcategories:
      - scientific_method
      - history_of_science
  web_tech:
    title: Web Technologies
    subcategories:
      - html&css
      - javascript
      - web_frameworks
  design:
    title: Design
    subcategories:
      - ui&ux
      - graphic_design

# Detailed category descriptions
categories:
  - name: python
    title: Python
    description: Python programming, including libraries and frameworks
  - name: html-css
    title: HTML & CSS
    description: Web development fundamentals
  - name: web-automation
    title: Web Automation
    description: Web scraping and automation techniques
  - name: data_analysis
    title: Data Analysis
    description: Tools and techniques for analyzing data
  - name: machine_learning
    title: Machine Learning
    description: ML algorithms, frameworks, and applications
  - name: data_visualization
    title: Data Visualization
    description: Tools and techniques for visualizing data
  - name: containerization
    title: Containerization
    description: Docker and container technologies
  - name: orchestration
    title: Orchestration
    description: Kubernetes and container orchestration
  - name: version_control
    title: Version Control
    description: Git and version control systems
  - name: monitoring
    title: Monitoring & Logging
    description: System monitoring and log analysis
  - name: etl
    title: ETL Processes
    description: Extract, Transform, Load processes and tools
  - name: stream_processing
    title: Stream Processing
    description: Real-time data streaming and processing
  - name: genomics
    title: Genomics
    description: Analysis of genomic data
  - name: proteomics
    title: Proteomics
    description: Study of proteins and their structures
  - name: ui-ux
    title: UI/UX Design
    description: User interface and experience design
  - name: graphic_design
    title: Graphic Design
    description: Visual design and illustration

# Achievement category structure
achievement_categories:
  certificates:
    title: Certificates
    subcategories:
      - professional
      - academic
  education:
    title: Education
    subcategories:
      - courses
      - workshops
  awards:
    title: Awards
    subcategories:
      - professional
      - academic
  publications:
    title: Publications
    subcategories:
      - journal_articles
      - conference_papers
  projects:
    title: Projects
    subcategories:
      - personal
      - collaborative

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      path: ""
      type: categories
    values:
      layout: category