# Site settings
title: Allen's Blog
description: A blog about tech, science, and interdisciplinary studies
url: "https://allenkang92.github.io"
baseurl: ""  # baseurl 설정 추가
github_username: allenkang92
author: Allen Kang
email: ksw8841@knou.ac.kr

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Navigation menu
navigation:
  - title: Home
    url: /
  - title: Posts
    url: /posts.html
  - title: Achievements
    url: /achievements.html
  - title: Tools
    url: /tools.html
  - title: About
    url: /about.html

# Collections
collections:
  categories:
    output: true
  tools:
    output: true

# Category structure for the blog
category_structure:
  programming:
    title: Programming
    subcategories:
      - python
      - java
      - web-automation
  data_science:
    title: Data Science
    subcategories:
      - machine_learning
      - data_analysis
      - data_visualization
  devops:
    title: DevOps & Cloud
    subcategories:
      - containerization
      - cloud_computing
      - orchestration
      - version_control
      - monitoring
  data_engineering:
    title: Data Engineering
    subcategories:
      - etl
      - stream_processing
  bioinformatics:
    title: Bioinformatics
    subcategories:
      - genomics
      - proteomics
  science_philosophy:
    title: Science Philosophy & History
    subcategories:
      - scientific_method
      - history_of_science
  web_tech:
    title: Web Technologies
    subcategories:
      - html&css
      - javascript
      - web_frameworks
  design:
    title: Design
    subcategories:
      - ui&ux
      - graphic_design

# Defaults for different content types
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      path: ""
      type: categories
    values:
      layout: category
