title: Allen's Blog
description: A blog about tech, science, and interdisciplinary studies
url: "https://allenkang92.github.io"
github_username: allenkang92

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

navigation:
  - title: Home
    url: /
  - title: Posts
    url: /posts.html
  - title: About
    url: /about.html
  - title: Tools
    url: /tools.html
  - title: Certificates
    url: /certificates.html

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Custom settings
author: Allen Kang
email: ksw8841@knou.ac.kr

# Collections
collections:
  categories:
    output: true

category_structure:
  programming:
    title: Programming
    subcategories:
      - python
      - html-css
      - web-automation
  data_science:
    title: Data Science
    subcategories:
      - data_analysis
      - machine_learning
      - data_visualization
  devops:
    title: DevOps & Cloud
    subcategories:
      - containerization
      - orchestration
      - version_control
      - monitoring
  data_engineering:
    title: Data Engineering
    subcategories:
      - etl
      - stream_processing
  bioinformatics:
    title: Bioinformatics
    subcategories:
      - genomics
      - proteomics
  design:
    title: Design
    subcategories:
      - ui-ux
      - graphic_design

categories:
  - name: python
    title: Python
    description: Python programming, including libraries and frameworks
  - name: html-css
    title: HTML & CSS
    description: Web development fundamentals
  - name: web-automation
    title: Web Automation
    description: Web scraping and automation techniques
  - name: data_analysis
    title: Data Analysis
    description: Tools and techniques for analyzing data
  - name: machine_learning
    title: Machine Learning
    description: ML algorithms, frameworks, and applications
  - name: data_visualization
    title: Data Visualization
    description: Tools and techniques for visualizing data
  - name: containerization
    title: Containerization
    description: Docker and container technologies
  - name: orchestration
    title: Orchestration
    description: Kubernetes and container orchestration
  - name: version_control
    title: Version Control
    description: Git and version control systems
  - name: monitoring
    title: Monitoring & Logging
    description: System monitoring and log analysis
  - name: etl
    title: ETL Processes
    description: Extract, Transform, Load processes and tools
  - name: stream_processing
    title: Stream Processing
    description: Real-time data streaming and processing
  - name: genomics
    title: Genomics
    description: Analysis of genomic data
  - name: proteomics
    title: Proteomics
    description: Study of proteins and their structures
  - name: ui-ux
    title: UI/UX Design
    description: User interface and experience design
  - name: graphic_design
    title: Graphic Design
    description: Visual design and illustration
    
# Defaults
defaults:
  - scope:
      path: ""
      type: categories
    values:
      layout: category