# Site settings
title: Allen's Blog
description: Striving for a better tomorrow, together with you.
url: "https://allenkang92.github.io"
github_username: allenkang92
author: Allen Kang
email: ksw8841@knou.ac.kr

# Build settings
markdown: kramdown
theme: minima
future: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - webpack.config.js
  - .babelrc
  - README.md

# Include specific files
include:
  - assets/js/dist/

# Navigation menu
navigation:
  - title: Home
    url: /
  - title: Posts
    url: /posts.html
  - title: Achievements
    url: /achievements.html
  - title: Tools
    url: /tools.html
  - title: About
    url: /about.html

# Collections
collections:
  categories:
    output: true
    permalink: /categories/:name/
  tools:
    output: true
  series:
    output: true
    permalink: /series/:name/
  achievements:
    output: true
    permalink: /achievements/:name/
  projects:
    output: true
    permalink: /projects/:title/
    hidden: true  # 직접 URL 접근 방지

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
      type: "achievements"
    values:
      layout: "achievement"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project_detail"
      hidden: true  # 프로젝트 페이지 숨김 처리
  - scope:
      path: "_data/achievement_categories.yml"
    values:
      layout: achievement

# Category structure for the blog
category_structure:
  programming:
    title: Programming
    subcategories:
      - python
      - java
      - web-automation
  data_science:
    title: Data Science
    subcategories:
      - data_analysis
      - machine_learning
      - deep_learning
      - data_visualization
  devops_and_cloud:
    title: DevOps & Cloud
    subcategories:
      - containerization
      - cloud_computing
      - orchestration
      - version_control
      - monitoring
  data_engineering:
    title: Data Engineering
    subcategories:
      - etl
      - stream_processing
  computer_science:
    title: Computer Science
    subcategories:
      - algorithms
      - data_structures
      - databases
      - networking
      - security
      - operating_systems
      - computer_architecture
      - software_engineering
      - programming_languages
      - quantum_computing
  bioinformatics:
    title: Bioinformatics
    subcategories:
      - genomics
      - proteomics
      - biopython
      - life_sciences
  science_philosophy_history:
    title: Science Philosophy & History
    subcategories:
      - philosophy_of_science
      - history_of_science
  mathematics_philosophy_history:
    title: Mathematics Philosophy & History
    subcategories:
      - philosophy_of_mathematics
      - history_of_mathematics
  web_technologies:
    title: Web Technologies
    subcategories:
      - html_css
      - javascript
      - web_frameworks
  design:
    title: Design
    subcategories:
      - ui_ux
      - graphic_design
  physics:
    title: Physics
    subcategories:
      - classical_mechanics
      - quantum_mechanics
      - relativity
  chemistry:
    title: Chemistry
    subcategories:
      - organic_chemistry
      - inorganic_chemistry
      - physical_chemistry
  cognitive_science:
    title: Cognitive Science
    subcategories:
      - cognitive_psychology
      - neuroscience
      - artificial_intelligence
  human_factors_engineering:
    title: Human Factors Engineering
    subcategories:
      - ergonomics
      - human_computer_interaction
  environmental_science:
    title: Environmental Science
    subcategories:
      - climate_change
      - sustainability
  social_impact:
    title: Social Impact
    subcategories:
      - technology_ethics
      - social_innovation
  sports_science:
    title: Sports Science
    subcategories:
      - biomechanics
      - exercise_physiology
  law:
    title: Law
    subcategories:
      - intellectual_property
      - technology_law
  mechanical_engineering:
    title: Mechanical Engineering
    subcategories:
      - thermodynamics
      - fluid_mechanics
  atmospheric_science:
    title: Atmospheric Science
    subcategories:
      - meteorology
      - climatology
  psychology:
    title: Psychology
    subcategories:
      - cognitive_psychology
      - social_psychology
  daily_life:
    title: Daily Life
    subcategories:
      - personal
      - travel
      - hobbies
      - reflections
      - work
      - self_improvement
      - tech_experiences
      - social_life
      - entertainment
      - food
      - fitness
      - relationships
      - education
      - culture
      - politics
      - environment
      - media
      - literature
      - music

# 이미지 최적화 설정
image_processing:
  resize:
    enable: true
    width: 1200
    height: 800
    quality: 85
  thumbnails:
    enable: true
    width: 400
    height: 300
    quality: 75

# 성능 최적화 설정
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: [html, head, body]

# 사이트 기능 설정
features:
  search: true
  related_posts: true
  image_lightbox: true
  code_copy: true
  math_equations: true
  loading_animation: true

# Assets
assets:
  sources:
    - assets/js

# JavaScript processing
js_dir: assets/js

# WebRick configuration for Content Security Policy
webrick:
  headers:
    Content-Security-Policy: >-
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdnjs.cloudflare.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https:;
      connect-src 'self' https:;
# 추가된 설정
destination: ./_site